# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
%run initialise.py

ModuleNotFoundError: No module named 'mdutils'

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
print(np.show_config())

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Femi/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Femi/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Femi/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Femi/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Femi/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Femi/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Femi/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Femi/anaconda3\\Library\\include']
None


#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
v1 = np.zeros(10)
v1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
# "%d bytes" % (null_vector.size * null_vector.itemsize)
f'{v1.size * v1.itemsize} bytes'

'80 bytes'

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
v2 = np.zeros(10)
v2[4] = 1
v2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
v3 = np.arange(10,50)
v3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
reversed = v3[::-1]
reversed

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
v4 = np.arange(0,9).reshape(3,3)
v4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
v5 = [1,2,0,0,4,0]
indices = np.nonzero(v5)
indices

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [165]:
id_matrix = np.identity(3)
id_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
arr3 = np.random.randint(0,10,[3,3,3])
arr3

array([[[3, 3, 8],
        [6, 8, 9],
        [6, 1, 8]],

       [[0, 7, 7],
        [8, 8, 6],
        [3, 8, 5]],

       [[0, 6, 7],
        [9, 9, 5],
        [9, 5, 9]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
arr10 = np.random.randint(15,90,[10,10])
print(arr10.min())
print(arr10.max())

15
88


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
mean_val = np.random.randint(1,100,30).mean()
mean_val

45.03333333333333

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [168]:
arr_bord = np.ones((5,5))
arr_bord[1:-1, 1:-1] = 0
arr_bord

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [178]:
arr_ones = np.random.randint(1,10,(3,3))
new_arr = np.pad(arr_ones, pad_width=1, mode='constant', constant_values=0)
print(new_arr)

# new_shape = [x + 2 for x in arr_ones.shape]
# arr_bord2 = np.zeros(new_shape)
# arr_bord2[1:-1, 1:-1] = arr_ones
# print(new_shape)
# print(arr_bord2)


[[0 0 0 0 0]
 [0 7 2 7 0]
 [0 2 4 8 0]
 [0 1 8 2 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [181]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [192]:
# mat5 = np.zeros((5,5))
# values = [1,2,3,4]
# for row_idx, val in enumerate(values):
#     col_idx = row_idx + 1
#     mat5[col_idx, row_idx] = val

mat5 = np.diag(1+np.arange(4), k=-1)
mat5

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [197]:
# def checkerboard(n,m,func) -> list:
#     '''Create a multi-dimensional checkerboard matrix'''
#     if func.__name__ != 'zeros':
#         raise Exception('Please pass in the numpy.zeros function')

#     matrix = func((n,m))
#     col, row = matrix.shape
#     for col_idx in range(0, col):
#         for row_idx in range(0, row):
#             pattern_one = col_idx % 2 == 0 and row_idx % 2 == 1
#             pattern_two = col_idx % 2 == 1 and row_idx % 2 == 0
#             if pattern_one or pattern_two:
#                 matrix[col_idx, row_idx] = 1

#     return matrix

# mat8 = checkerboard(8,8,np.zeros)

mat8 = np.zeros((8, 8), dtype=int)
mat8[1::2, ::2] = 1
mat8[::2, 1::2] = 1
mat8


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [199]:
pos = 100
shape = (6,7,8)
idx = np.unravel_index(pos - 1, shape)
idx

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [200]:
size = np.array([8,8])
tiler = np.array([0,1,1,0]).reshape(2,2)
tile_shape = (size / 2).astype(int)
tiled = np.tile(tiler, tile_shape)
tiled

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [202]:
mat5 = np.random.random([5,5])
normalized = (mat5 - np.mean(mat5)) / np.std(mat5)
print(mat5)
print(normalized)

[[0.74520148 0.09315704 0.57756446 0.97905213 0.08554312]
 [0.73613853 0.13304946 0.68968298 0.38644287 0.79707185]
 [0.62134726 0.21688076 0.23880469 0.18645388 0.54676918]
 [0.38935208 0.89580401 0.53088986 0.1393687  0.89214544]
 [0.22898697 0.50918227 0.77574038 0.50593169 0.34757905]]
[[ 0.93890606 -1.45931698  0.32233617  1.79901005 -1.487321  ]
 [ 0.90557251 -1.31259242  0.73470873 -0.38061007  1.12968559]
 [ 0.48336957 -1.00426046 -0.92362413 -1.11617068  0.209071  ]
 [-0.36991     1.49282302  0.15066676 -1.28935023  1.47936678]
 [-0.95973373  0.07082613  1.05122831  0.05887047 -0.52355142]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [204]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [205]:
mat1 = np.random.randint(1,10, [5,3])
mat2 = np.random.randint(1,10, [3,2])
print(mat1)
print(mat2)
print(np.matmul(mat1, mat2))
print(np.dot(mat1, mat2))

[[6 5 1]
 [2 1 8]
 [2 6 9]
 [6 1 7]
 [3 5 5]]
[[8 6]
 [1 1]
 [9 2]]
[[ 62  43]
 [ 89  29]
 [103  36]
 [112  51]
 [ 74  33]]
[[ 62  43]
 [ 89  29]
 [103  36]
 [112  51]
 [ 74  33]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [217]:
arr1d = np.random.randint(1,10, 20)
arr1d_copy = arr1d.copy()
print(arr1d)
mask = (arr1d > 3) & (arr1d < 8)

# Method 1
np.negative(arr1d, where=mask, out=arr1d)
print(arr1d)

# Method 2
arr1d_copy[mask] *= -1
print(arr1d_copy)




[4 7 5 7 6 7 6 9 4 2 6 7 2 4 7 9 1 6 3 9]
[-4 -7 -5 -7 -6 -7 -6  9 -4  2 -6 -7  2 -4 -7  9  1 -6  3  9]
[-4 -7 -5 -7 -6 -7 -6  9 -4  2 -6 -7  2 -4 -7  9  1 -6  3  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [221]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-221-cd809174da5d>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
<ipython-input-221-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [242]:
arr1 = np.random.randint(1,20, 10)
arr2 = np.random.randint(1,20, 10)
print(arr1)
print(arr2)

# Method 1
mask = np.isin(arr1, arr2)
common = np.unique(arr1[mask])
print(common)

# Method 2
common2 = np.intersect1d(arr1, arr2)
print(common2)


[11 14 18  9  6 19 10  3 19 10]
[15  2 10  9 18  6 14 18  9 16]
[ 6  9 10 14 18]
[ 6  9 10 14 18]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [243]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1)
print(yesterday, today, tomorrow)

2021-11-18 2021-11-19 2021-11-20


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [246]:
july = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(july)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [248]:
import math
arr1 = np.random.random(10) * 100
print(arr1)
# integers = [math.trunc(x) for x in arr1]
integers = np.trunc(arr1).astype(int)
print(integers)

[89.14636783 68.07517987 13.39774417 81.27846228  4.42347268 42.29872896
 42.43257104 29.29416703 60.50263632 21.52021035]
[89 68 13 81  4 42 42 29 60 21]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [260]:
# low, high = 0, 4
# size = (5,5)
# mat5 = np.random.randint(low, high + 1, np.prod(size)).reshape(size)
# mat5

Z = np.arange(5)
Z = np.tile(Z, [5,1])
print(Z)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [81]:
gen_int = np.random.randint(1,10,10)
arr = np.array(gen_int)
arr

array([2, 8, 6, 8, 1, 8, 6, 6, 9, 7])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [261]:
Z = np.linspace(0, 1, 11, endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [84]:
rand_arr = np.random.random(10)
np.sort(rand_arr)

array([0.03252723, 0.1591076 , 0.19764234, 0.23044437, 0.5856893 ,
       0.69922506, 0.80321034, 0.86682917, 0.92954886, 0.94116305])

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [271]:
arr1 = np.random.randint(1,10,3)
arr2 = np.random.randint(1,10,3)
print(arr1)
print(arr2)

is_equal = np.equal(arr1,arr2).all()
print(is_equal)

is_equal2 = np.array_equal(arr1, arr2)
print(is_equal2)


[4 6 8]
[7 8 4]
False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [272]:
arr = np.array(np.arange(5))
arr.flags.writeable = False
arr[2] = 299
arr

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [282]:
arr = np.random.randint(1, 10,10)
arr2 = arr.copy()

# Method 1
highest = np.max(arr)
arr = [0 if x == highest else x for x in arr]
print(arr)

# Method 2
idx_max = arr2.argmax()
arr2[idx_max] = 50
print(arr2)


[1, 1, 5, 2, 3, 3, 7, 0, 3, 7]
[ 1  1  5  2  3  3  7 50  3  7]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [289]:
arr1 = np.arange(10)
arr2 = np.random.uniform(0, 10)
print(arr1)
print(arr2)
print(arr1 - arr2)
index = (np.abs(arr1 - arr2)).argmin()
print(arr1[index])

[0 1 2 3 4 5 6 7 8 9]
3.7197084903396247
[-3.71970849 -2.71970849 -1.71970849 -0.71970849  0.28029151  1.28029151
  2.28029151  3.28029151  4.28029151  5.28029151]
4


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)